### ISSUE TITLE
添加docker支持

### ISSUE THREAD

**Issue by Lxeon** [heiher/natmap#54]
Dockerfile:
```
FROM ubuntu:latest
ENV LANG        C.UTF-8
ENV LANGUAGE    C.UTF-8
ENV LC_ALL      C.UTF-8
RUN apt update \
    && apt upgrade -y \
    && apt install -y gcc git make curl
RUN git clone --recursive https://github.com/heiher/natmap.git \
    && cd natmap \
    && make \
    && cp ./bin/natmap /opt/natmap
ENTRYPOINT ["/opt/natmap"]
```

构建镜像
```
docker build -f ./dockerfiles/natmap/Dockerfile -t natmap .
```

docker-compose.yml
```
  natmap-wg:
    container_name: natmap-wg
    image: natmap
    command: -u -s stun.qq.com -b 30101 -t 127.0.0.1 -p 51820 -e /opt/cf_ip4p.sh -k 60
    volumes:
      - ./natmap/cf_ip4p.sh:/opt/cf_ip4p.sh
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TZ=Asia/Shanghai
    network_mode: host
    restart: always
```

如果用python脚本的话，需要exec到容器内，再apt update && apt install python，其他的类似
